services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis-data:/data
    environment:
      REDIS_ARGS: --save 300 1 60 10
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  redis-data:
    driver: local
